### ISSUE TITLE
<Form> + File[] field is not mapped to FormData correctly

### ISSUE THREAD

**Issue by OkayX6** [forge42dev/remix-hook-form#113]
Hi,

**Version:** `4.3.0` but also `5.1.0`

## Symptom
When using the `useRemixForm<>()` naively

Using this schema: 
```typescript
const dataRequestSchema = z.object({
  // A pure HTML Input with multiple files would have type 'FileList'
  // But our usage of react-dropzone + react-hook-form controller sends an array of File
  files: z.array(z.instanceof(File)),
  comments: z.string().nullable(),
})
```

The files param is not mapped correctly like it should in the `FormData` (Chrome request window) - it is serialized as an array of strings:

![image](https://github.com/user-attachments/assets/aeeb875a-ef4e-4e67-8f26-aee7d216ccf2)

--
I had to define a custom `submitHandler`

```typescript
const form = useRemixForm<DataRequest>({
    resolver: zodResolver(dataRequestSchema),
    submitHandlers: {
      onValid: (data) => {
        const formData = new FormData()
        // Send a File[] called 'files'
        for (const file of data.files) {
          formData.append('files', file)
        }
       ...
```

Not sure if the fix is complex =)

**Comment by AlemTuzlak** [comment]
should work now with 5.1.1, please re-open if not the case
