### ISSUE TITLE
[help] Using remix-hook-form in a component (not a route)

### ISSUE THREAD

**Issue by genox** [forge42dev/remix-hook-form#125]
Hi,

How would yo go about linking up a form within a modal that is not technically part of any route, thus cannot POST directly?

Is it possible to choose a target route manually that could handle the form submission?

Also, is it possible to fall back to regular client side validation? All my shadcn Form components depend on Remix Hook Form context and it would be nice to have an option for fallback, in case server side handling is not available.

Thanks for any hints!

**Comment by AlemTuzlak** [comment]
you can pass in a custom fetcher and it will submit to that fetcher instead of the current route, I think that would allow you to submit anywhere?

**Comment by DevTGhosh** [comment]
hey @AlemTuzlak  in a similar vain how would I submit a form that is in a custom component in a route?

**Comment by DevTGhosh** [comment]
> if it's a custom component submitting to the current route, you don't need anything else other than the hook, otherwise if it's submitting to a different route, again, a custom fetcher will do!

You mean the `useRemixForm` hook? I am putting that in the custom component as well but that is causing the action on the route to not fire.

**Comment by AlemTuzlak** [comment]
yes, but the reason it doesn't work in your case is because you're using the <Form element there iwthout the action prop, either set it to the current route or set it in the submitConfig of the hook

**Comment by DevTGhosh** [comment]
@AlemTuzlak thank you that solved my issue. Great job on the yt videos and this library.

**Comment by genox** [comment]
@AlemTuzlak Thank you!
