### ISSUE TITLE
React Router v7 peer dependency 

### ISSUE THREAD

**Issue by LeoDanielsson** [forge42dev/remix-hook-form#126]
Will this package be updated to replace the @remix-run/react peer dependency with react-router?

**Comment by AlemTuzlak** [comment]
Tomorrow most likely new major

**Comment by mjjabarullah** [comment]
We are waiting!!

**Comment by AlemTuzlak** [comment]
published with v6

**Comment by AlemTuzlak** [comment]
https://github.com/forge42dev/remix-hook-form/releases/tag/v6.0.0

**Comment by mjjabarullah** [comment]
it working cool in RR7
