### ISSUE TITLE
getValidatedFormData broken in 6.0.0?

### ISSUE THREAD

**Issue by hauptrolle** [forge42dev/remix-hook-form#135]
When using `v5.0.4` the returned data is in the correct shape of the given validator. In `v6.0.0` I only get `any` for the returned data.

**Comment by ndozhh** [comment]
Hello @AlemTuzlak 

I confirm this is happening in the latest version, any chance we can get a fix for this?

![image](https://github.com/user-attachments/assets/43acb064-ca4f-4417-815a-43e51072f840)

I'm also using the previous version with Remix and it's working great.

**Comment by AlemTuzlak** [comment]
Checking out today

**Comment by hauptrolle** [comment]
@AlemTuzlak Looks like it is released on GitHub but not published to npm 🙈

**Comment by AlemTuzlak** [comment]
@hauptrolle I am so sorry, looks like something went wrong with the publish workflow, manually published just now!
