### ISSUE TITLE
TypeScript: Return type of useRemixForm hook is incorrect.

### ISSUE THREAD

**Issue by piotrkulpinski** [forge42dev/remix-hook-form#75]
Hi, 
Thanks for building this package! 
I'm trying to migrate my app from remix-validated-form to this one but I've run into some issue regarding TS types. 

Loos like `useRemixForm` is incorrectly returning form types. 

Here's the type returned from `react-hook-form`:
![CleanShot 2024-02-07 at 15 05 53](https://github.com/Code-Forge-Net/remix-hook-form/assets/358412/5d382bb6-7912-40c4-956a-fcb56b892079)

...and here's `remix-hook-form`:
![CleanShot 2024-02-07 at 15 05 44](https://github.com/Code-Forge-Net/remix-hook-form/assets/358412/38ac1ee9-9352-4a29-8e02-e7a90b681383)

You can see the values are incorrectly typed as undefined. According to the zod schema, those fields should never be undefined just like in the first example.

```ts
const schema = z.object({
  name: z.string().trim().min(3).max(32),
  slug: z.string().trim().min(3).max(32),
})
```

**Comment by AlemTuzlak** [comment]
hi @piotrkulpinski, I'll look into this but you can pass in the schema type as a workaround and it will work correctly, eg. `useRemixForm<YourSchema>()`

**Comment by piotrkulpinski** [comment]
> hi @piotrkulpinski, I'll look into this but you can pass in the schema type as a workaround and it will work correctly, eg. `useRemixForm<YourSchema>()`

Tried that, but this has given me even bigger problems with typing the models correctly. 

![CleanShot 2024-02-12 at 13 23 43](https://github.com/Code-Forge-Net/remix-hook-form/assets/358412/714d051e-3f2f-4e4e-b2d9-a191578878b2)

**Comment by AlemTuzlak** [comment]
Hmm can you guys install the latest versions of remix-hook-form and react-hook-form and let me know if that resolves it? It could be a mismatch between the versions, but what is important to note is that the return types ARE different, there are a few changes added on top of react-hook-form so they can't be identical, like handleSubmit, register, reset etc are enhanced for remix use-cases

**Comment by usr3** [comment]
Hi @AlemTuzlak, any way you can expose the equivalent type of `UseFormReturn` which `remix-hook-form` is using? I'm passing the form object to a custom hook so no way to init the form there.
```
export function useSomeCustomHook(
  setSomeState: React.Dispatch<React.SetStateAction<boolean>>,
  form: UseFormReturn,
) {..}
```

**Comment by makrandgupta** [comment]
Running into the same issue. I have the latest versions of both `react-hook-form` and `remix-hoko-form`. 

Here's the error I am seeing:
```
Type '{ children: Element; handleSubmit: (e?: BaseSyntheticEvent<object, any, any> | undefined) => Promise<void>; reset: (values?: { email: string; password: string; } | { ...; } | undefined, options?: Partial<...> | undefined) => void; ... 12 more ...; setFocus: UseFormSetFocus<...>; }' is not assignable to type 'UseFormReturn<{ email: string; password: string; }, any, undefined>'.
  Types of property 'reset' are incompatible.
    Type '(values?: { email: string; password: string; } | { email?: string | undefined; password?: string | undefined; } | undefined, options?: Partial<{ keepDirtyValues: boolean; keepErrors: boolean; keepDirty: boolean; ... 7 more ...; keepSubmitCount: boolean; }> | undefined) => void' is not assignable to type 'UseFormReset<{ email: string; password: string; }>'.
      Types of parameters 'values' and 'values' are incompatible.
        Type '{ email: string; password: string; } | { email?: string | undefined; password?: string | undefined; } | ResetAction<{ email: string; password: string; }> | undefined' is not assignable to type '{ email: string; password: string; } | { email?: string | undefined; password?: string | undefined; } | undefined'.
          Type 'ResetAction<{ email: string; password: string; }>' is not assignable to type '{ email: string; password: string; } | { email?: string | undefined; password?: string | undefined; } | undefined'.ts(2322)
```

My code:

```ts


const schema = z.object({
  email: z
    .string({ required_error: "Email is required" })
    .email("Email is invalid"),
  password: z.string({ required_error: "Password is required" }),
});
type FormData = z.infer<typeof schema>;


// Form component is from shadcn
export default function Login() {
  const form = useRemixForm<FormData>({
    mode: "onSubmit",
    resolver,
  });
  return (
      <Form {...form}>
        <form onSubmit={form.handleSubmit} className="space-y-8">
          <FormField
            control={form.control}
            name="email"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Email</FormLabel>
                <FormControl>
                  <Input placeholder="shadcn" {...field} />
                </FormControl>
                <FormDescription>
                  This is your public display name.
                </FormDescription>
                <FormMessage />
              </FormItem>
            )}
          />
          <FormField
            control={form.control}
            name="password"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Password</FormLabel>
                <FormControl>
                  <Input placeholder="shadcn" {...field} />
                </FormControl>
                <FormDescription>
                  This is your public display name.
                </FormDescription>
                <FormMessage />
              </FormItem>
            )}
          />
          <Button type="submit">Submit</Button>
        </form>
      </Form>
  );
}
```

**Comment by AlemTuzlak** [comment]
@makrandgupta It seems you're using the FormProvider from `react-hook-form` the two are not interchangeable as the `remix-hook-form` package augments certain functions to allow for easier handling in Remix.
@usr3 I now export UseRemixFormReturn type

**Comment by AlemTuzlak** [comment]
a lot of issues arise from the fact that remix-hook-form has different types compared to react-hook-form, I'm closing this for now as this was opened a while ago and I've changed the signatures of many of these functions, please feel free to open new issues!
