### ISSUE TITLE
Form Reset On Success

### ISSUE THREAD

**Issue by AlexanderKaran** [forge42dev/remix-hook-form#81]
Once the submission is successful, I have a form that stays on the same page once the action is complete (account page in settings).

I need the form to reset (i.e. isDirty) to go back to false.

Is there a way to do this without using a useEffect? Totally happy to contribute to the docs

**Comment by chiptus** [comment]
```ts
  const [formKey, clearForm] = useReducer((state) => state + 1, 0);

  <FormComponent key={formKey} onSuccess={() => clearForm()} />
  
  ```

**Comment by AlemTuzlak** [comment]
@Roanmh Yes, I discovered that some methods were unstable in between renders and caused the issue but they were fixed. I would recommend just using the intended approach from the `react-hook-form` docs or what Chiptus wrote in his comment

**Comment by theskillwithin** [comment]
still experiencing

**Comment by vincaslt** [comment]
Same, not sure if it used to happen before, but on latest version 5.1.1 it is happening: passing `form` to useEffect will enter render loop, but assigning `form.reset` works
