### ISSUE TITLE
Allow `encType: "application/json"` from `submitConfig`

### ISSUE THREAD

**Issue by edbella** [forge42dev/remix-hook-form#93]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `remix-hook-form@4.3.1` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/remix-hook-form/dist/index.js b/node_modules/remix-hook-form/dist/index.js
index 6fd94e4..cd0637a 100644
--- a/node_modules/remix-hook-form/dist/index.js
+++ b/node_modules/remix-hook-form/dist/index.js
@@ -130,8 +130,9 @@ var useRemixForm = ({
   const onSubmit = useMemo(
     () => (data2) => {
       setIsSubmittedSuccessfully(true);
-      const formData = createFormData(
-        { ...data2, ...submitData },
+      const submitPayload = { ...data2, ...submitData };
+      const formData = submitConfig?.encType === 'application/json' ? submitPayload : createFormData(
+        submitPayload,
         stringifyAllValues
       );
       submit(formData, {
```

I noticed that when I set the `encType` value to `application/json` in the `submitConfig`, the data being sent still remained as `FormData`.

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by CestDiego** [comment]
Yes please! This is super important to me as I'm trying to also use the useFieldArray from react-hook-form.

**Comment by nelsliu9121** [comment]
I believe you should make this into an PR.
