### ISSUE TITLE
Version 4.3.1 Missing

### ISSUE THREAD

**Issue by Roanmh** [forge42dev/remix-hook-form#97]
The [NPM page](https://www.npmjs.com/package/remix-hook-form/v/4.3.1) for this project shows a version 4.3.1 and [this commit](https://github.com/forge42dev/remix-hook-form/commit/85a584f3975698e18aa7845bdd9c360e8ba50bf6) references the same version. I also remember seeing it earlier today.

Now as I look, the latest release on Github is 4.3.0 and the tag `v4.3.1` does not exist. However the main branch still shows the commit above.

<img width=40% alt="github" src="https://github.com/forge42dev/remix-hook-form/assets/10479270/6f866b67-17e9-4a4b-acb6-aa86b3dbb2c0">

<img width=40% alt="npm" src="https://github.com/forge42dev/remix-hook-form/assets/10479270/ab882b13-61ee-4197-90b2-bb31f6417a11">

Was this action intentional? Is there a bug or issue with those changes?

Thank you

**Comment by AlemTuzlak** [comment]
@Roanmh I unfortunately forgot to create a release on Github but pushed it to npm as a quick bug fix, it does indeed exist it's just not documented on Github, sorry about that!
