### ISSUE TITLE
Document `preserveStringified` on `getValidatedFormData`

### ISSUE THREAD

**Issue by KarstenBuckstegge** [forge42dev/remix-hook-form#99]
The third argument of `getValidatedFormData` is not described in the documentation. Therefor a string value that only contains numbers being passed into `getValidatedFormData` is automagically converted to a number, causing unexpected validation errors.

Documenting the `preserveStringified` attribute will explain that behaviour.

**Comment by timvandam** [comment]
I encountered this as well. Also wonder why the defaults expect everything to be json. That does not make much sense to me as pretty much all forms I implement are just raw text or numbers that zod will coerce for me

**Comment by AlemTuzlak** [comment]
I documented the behavior in the readme!
